kind: Service
apiVersion: v1
metadata:
  name: backend-service
  namespace: travelmania
  labels:
    app: travelmania
spec:
  type: NodePort
  labels:
    app: travelmania
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    NodePort: 31100
