kind: Deployment 
apiVersion: apps/v1
metadata: 
  name: mongodb-deployment
  namespace: travelmania
  labels:
    app: travelmania
spec:
  replicas: 3
  selector:
    matchLabels:
      app: travelmania
  template:
    metadata:
      labels:
        app: travelmania 
    spec:
      containers:
      - name: mongodb
        image: mongodb:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/lib
      volumes: 
      - name: mongo-storage
        persistentVolumeClaim:
              claimName: mongo-pvc