kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo-pv
  namespace: travelmania
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/db